/* [1] Create database user */
CREATE USER 'ttCalendar'@'10.182.20.12' IDENTIFIED BY 'ttCalendar';
GRANT ALL PRIVILEGES ON *.* TO 'ttCalendar'@'10.182.20.12' WITH GRANT OPTION;
CREATE USER 'ttCalendar'@'%' IDENTIFIED BY 'ttCalendar';
GRANT ALL PRIVILEGES ON *.* TO 'ttCalendar'@'%' WITH GRANT OPTION;

/* [2] Create schema */
CREATE SCHEMA IF NOT EXISTS `ttCalendar` DEFAULT CHARACTER SET utf8;

/* [3] Init Tables & Views */
DROP TABLE IF EXISTS `ttCalendar`.`USER`;
DROP TABLE IF EXISTS `ttCalendar`.`USER_COMMON`;
DROP TABLE IF EXISTS `ttCalendar`.`USER_TYPE_CODE`;

/* [4] Create Tables */
/* Create Table USER */
CREATE TABLE IF NOT EXISTS `ttCalendar`.`USER` (
  `USER_ID` INT NOT NULL,
  `USER_TYPE` VARCHAR(3) NOT NULL,
  `ROLE` INT NOT NULL,
  `DEL_FLG` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`USER_ID`))
ENGINE = InnoDB;

/* Create Table USER_COMMON */
CREATE TABLE IF NOT EXISTS `ttCalendar`.`USER_COMMON` (
  `USER_ID` INT NOT NULL,
  `USER_NAME` VARCHAR(45) NOT NULL,
  `USER_PASSWORD` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(45) NULL,
  `DEL_FLG` VARCHAR(1) NOT NULL,
  `USER_COMMONcol` VARCHAR(45) NULL,
  INDEX `fk_USER_COMMON_USER_idx` (`USER_ID` ASC),
  PRIMARY KEY (`USER_ID`, `USER_NAME`),
  CONSTRAINT `fk_USER_COMMON_USER`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `ttCalendar`.`USER` (`USER_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

/* Create Table USER_TYPE_CODE */
CREATE TABLE IF NOT EXISTS `ttCalendar`.`USER_TYPE_CODE` (
  `TYPE_CODE` VARCHAR(3) NOT NULL,
  `TYPE_NAME` VARCHAR(45) NOT NULL,
  `DEL_FLG` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`TYPE_CODE`))
ENGINE = InnoDB;

/* Create Table USER_ROLE_CODE */
CREATE TABLE IF NOT EXISTS `ttCalendar`.`USER_ROLE_CODE` (
  `ROLE_CODE` INT NOT NULL,
  `ROLE_NAME` VARCHAR(45) NOT NULL,
  `DEL_FLG` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`ROLE_CODE`))
ENGINE = InnoDB;

/* [5] Import Default values */
INSERT INTO `ttCalendar`.`USER` (USER_ID, USER_TYPE, ROLE, DEL_FLG) VALUES (1, '001', 1, '0');
INSERT INTO `ttCalendar`.`USER` (USER_ID, USER_TYPE, ROLE, DEL_FLG) VALUES (2, '001', 1, '0');
INSERT INTO `ttCalendar`.`USER` (USER_ID, USER_TYPE, ROLE, DEL_FLG) VALUES (3, '002', 1, '0');
INSERT INTO `ttCalendar`.`USER` (USER_ID, USER_TYPE, ROLE, DEL_FLG) VALUES (4, '001', 1, '1');

INSERT INTO `ttCalendar`.`USER_COMMON` (USER_ID, USER_NAME, USER_PASSWORD, EMAIL, DEL_FLG) VALUES (1, 'USER001', '666666', 'abc@163.com', '0');
INSERT INTO `ttCalendar`.`USER_COMMON` (USER_ID, USER_NAME, USER_PASSWORD, EMAIL, DEL_FLG) VALUES (2, 'USER002', '666666', NULL, '0');
INSERT INTO `ttCalendar`.`USER_COMMON` (USER_ID, USER_NAME, USER_PASSWORD, EMAIL, DEL_FLG) VALUES (3, 'USER003', '666666', 'abc@163.com', '0');
INSERT INTO `ttCalendar`.`USER_COMMON` (USER_ID, USER_NAME, USER_PASSWORD, EMAIL, DEL_FLG) VALUES (4, 'USER004', '666666', 'abc@163.com', '1');

INSERT INTO `ttCalendar`.`USER_TYPE_CODE` (TYPE_CODE, TYPE_NAME, DEL_FLG) VALUES ('001', 'COMMON', '0');
INSERT INTO `ttCalendar`.`USER_TYPE_CODE` (TYPE_CODE, TYPE_NAME, DEL_FLG) VALUES ('002', 'BAIDU',  '0');
INSERT INTO `ttCalendar`.`USER_TYPE_CODE` (TYPE_CODE, TYPE_NAME, DEL_FLG) VALUES ('003', 'QQ',     '0');
INSERT INTO `ttCalendar`.`USER_TYPE_CODE` (TYPE_CODE, TYPE_NAME, DEL_FLG) VALUES ('004', 'SINA',   '0');
INSERT INTO `ttCalendar`.`USER_TYPE_CODE` (TYPE_CODE, TYPE_NAME, DEL_FLG) VALUES ('005', 'REN',    '0');

INSERT INTO `ttCalendar`.`USER_ROLE_CODE` (ROLE_CODE, ROLE_NAME, DEL_FLG) VALUES (0, 'None', '0');
INSERT INTO `ttCalendar`.`USER_ROLE_CODE` (ROLE_CODE, ROLE_NAME, DEL_FLG) VALUES (1, 'USER', '0');
INSERT INTO `ttCalendar`.`USER_ROLE_CODE` (ROLE_CODE, ROLE_NAME, DEL_FLG) VALUES (9, 'ADMIN', '0');
