/* [1] Create database user */
CREATE USER 'ttCalendar'@'10.182.20.12' IDENTIFIED BY 'ttCalendar';
GRANT ALL PRIVILEGES ON *.* TO 'ttCalendar'@'10.182.20.12' WITH GRANT OPTION;
CREATE USER 'ttCalendar'@'%' IDENTIFIED BY 'ttCalendar';
GRANT ALL PRIVILEGES ON *.* TO 'ttCalendar'@'%' WITH GRANT OPTION;

/* [2] Create schema */
CREATE SCHEMA `ttCalendar` DEFAULT CHARACTER SET utf8 ;

/* [3] Init Tables & Views */
DROP TABLE IF EXISTS `ttCalendar`.`USER`;
DROP TABLE IF EXISTS `ttCalendar`.`USER_COMMON`;
DROP TABLE IF EXISTS `ttCalendar`.`USER_BAIDU`;
DROP TABLE IF EXISTS `ttCalendar`.`USER_QQ`;
DROP TABLE IF EXISTS `ttCalendar`.`USER_SINA`;
DROP TABLE IF EXISTS `ttCalendar`.`USER_REN`;

DROP TABLE `ttCalendar`.`USER_TYPE_CODE`;

/* [4] Create Tables */
/* Create Table USER */
CREATE TABLE `ttCalendar`.`USER` (
  `USER_ID` INT NOT NULL,
  `USER_NAME` VARCHAR(21) NOT NULL,
  `USER_TYPE` VARCHAR(3) NOT NULL,
  `DEL_FLG` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`USER_ID`, `USER_NAME`));
/* Create Table USER_COMMON */
CREATE TABLE `ttCalendar`.`USER_COMMON` (
  `USER_ID` INT NOT NULL,
  `USER_PASSWORD` VARCHAR(45) NOT NULL,
  `DEL_FLG` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`USER_ID`));
/* Create Table USER_BAIDU */
CREATE TABLE `ttCalendar`.`USER_BAIDU` (
  `USER_ID` INT NOT NULL,
  `USER_TOKEN` VARCHAR(100) NOT NULL,
  `DEL_FLG` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`USER_ID`));
  
/* Create Table USER_TYPE_CODE */
CREATE TABLE `ttCalendar`.`USER_TYPE_CODE` (
  `TYPE_CODE` VARCHAR(3) NOT NULL,
  `TYPE_NAME` VARCHAR(45) NOT NULL,
  `DEL_FLG` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`TYPE_CODE`));

/* [5] Import Default values */
INSERT INTO `ttCalendar`.`USER_TYPE_CODE` (TYPE_CODE, TYPE_NAME, DEL_FLG) VALUES ('001', 'COMMON', '0');
INSERT INTO `ttCalendar`.`USER_TYPE_CODE` (TYPE_CODE, TYPE_NAME, DEL_FLG) VALUES ('002', 'BAIDU',  '0');
INSERT INTO `ttCalendar`.`USER_TYPE_CODE` (TYPE_CODE, TYPE_NAME, DEL_FLG) VALUES ('003', 'QQ',     '0');
INSERT INTO `ttCalendar`.`USER_TYPE_CODE` (TYPE_CODE, TYPE_NAME, DEL_FLG) VALUES ('004', 'SINA',   '0');
INSERT INTO `ttCalendar`.`USER_TYPE_CODE` (TYPE_CODE, TYPE_NAME, DEL_FLG) VALUES ('005', 'REN',    '0');


